### ISSUE TITLE
Proposed PlaneAnnotation updates

### ISSUE THREAD

**Issue by rjackey** [mathworks/volume-labeling-widgets#17]
o	\+wt\+model\PlaneAnnotation.m:176 - X asked me to limit the displayed planes to be semi-infinite, so I added obj.Bounds = 150 * [-1,1; -1,1]; (I know it's not generic enough, but it worked well enough for X so I moved on to other tasks...)

**Comment by rjackey** [comment]
I am thinking the best solution for this is to set the hidden property "Bounds" rather than modify the code.  I'm not exactly sure the best way to do this in a generic way, as it depends on the imagery shown that is not known by the PlaneAnnotation.

**Comment by altmany** [comment]
how about moving Bounds from the Hidden,Protected properties block to the Public block? then users could modify this property when they instantiate

**Comment by rjackey** [comment]
Agreed - will do

**Comment by rjackey** [comment]
I can't remember exactly how these boundaries work to be honest.  I'm putting the Bounds in the public block with description as follows.  If there's a better description we can change it.

% Maximum display distance boundaries of the plane 
Bounds (2,2) double = [-1e6 1e6; -1e6 1e6];

**Comment by altmany** [comment]
perhaps add something like "_replace 1e6 with a small finite value to create a finite-sized plane_" to the description comment
